### ISSUE TITLE
 PutUserToSharedFolder Method Fails to Update Existing Users' Permissions in Shared Folder - Error: (key type required)

### ISSUE THREAD

**Issue by YoussefFenetre** [Keeper-Security/keeper-sdk-dotnet#135]
I'm experiencing an issue with the Keeper SDK when trying to update the permissions of existing users in a shared folder using the PutUserToSharedFolder method. While adding new users works correctly, attempting to update existing users' permissions results in an error indicating that a key type is required.

**Steps to Reproduce:**

1. Use the PutUserToSharedFolder method to add new users to a shared folder successfully.
2. Attempt to update the permissions of an existing user in the shared folder using the same method.
3. Observe that the method fails with an error message.

**Error Message and Stack Trace:**

Error adding users to shared folder: An error has occurred. Please check if an update is available for your device on the App Store or the Keeper Security website. If you continue to receive this error, please email support@keepersecurity.com or contact us at https://keepersecurity.com/support.html and let us know that error code (key type required) has occurred.

Error adding users to shared folder:    at KeeperSecurity.Authentication.KeeperEndpoint.ExecuteRest(String endpoint, ApiRequestPayload payload)
   at KeeperSecurity.Authentication.AuthCommon.ExecuteAuthRest(String endpoint, IMessage request, Type responseType, Int32 apiVersion)
   at KeeperSecurity.Authentication.AuthExtensions.ExecuteAuthRest[TC,TR](IAuthentication auth, String endpoint, TC request, Int32 apiVersion)
   at KeeperSecurity.Vault.VaultOnline.PutUserToSharedFolder(String sharedFolderUid, String userId, UserType userType, ISharedFolderUserOptions options)
   at MyAppNamespace.ViewModel.FolderManagerViewModel.AddUsersToSharedFolder(String sharedFolderUid)
   
   
**Additional Information:**

**Behavior Observed:**

- Adding new users to the shared folder using PutUserToSharedFolder works without issues.
- Updating permissions of existing users using the same method results in the error above.

**Analysis:**

- It appears that when updating existing users, the PutUserToSharedFolder method does not handle the operation correctly and requires additional parameters or modifications.
- Including the shared folder key in SharedFolderUserOptions is not feasible as per the method's intended usage and security considerations.

**Request:**

- Guidance: If there's an alternative recommended approach for updating existing users' permissions, please provide guidance on how to implement it using the Keeper SDK.

**Thank you for your assistance!**

If any additional information is needed, please let me know.

**Comment by sk-keeper** [comment]
Are you trying to add yourself to a shared folder?

**Comment by sk-keeper** [comment]
This issue could be duplicated when a user adds/modifies its permissions in a shared folder.
Add permissions error originates at the .Net SDK. The fix can be release any time.
Update its own permissions is a backend issue. It is already fixed by the backend team.
It is hard to tell when the fix will be released.

**Comment by sali-ks** [comment]
This issue is fixed with latest version hence closing the  issue.
